services:
  - type: web
    name: my-tesseract-app
    env: docker
    repo: https://github.com/Shidenaywedi/OCR
    region: oregon  # Change based on your preferred region
    plan: free
    autoDeploy: true
